# Generated by Django 4.1 on 2022-09-12 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skill', '0002_skillset_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration_spent', models.CharField(max_length=20)),
                ('joining_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experience.company')),
                ('technologies', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='skill.skill')),
            ],
            options={
                'verbose_name': ['Projects'],
            },
        ),
    ]
