# Generated by Django 4.1 on 2022-09-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project'},
        ),
        migrations.AlterField(
            model_name='company',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
