# Generated by Django 4.1 on 2022-09-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0002_skillset_image'),
        ('experience', '0003_alter_company_duration_spent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='technologies',
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(blank=True, null=True, related_name='skills', to='skill.skill'),
        ),
    ]
