# Generated by Django 4.1 on 2022-09-17 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0004_remove_project_technologies_project_technologies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['-joining_date']},
        ),
        migrations.AddField(
            model_name='company',
            name='responsibility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsibilities', to='experience.responsibility'),
        ),
    ]
