# Generated by Django 4.1 on 2022-09-18 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0005_responsibility_alter_company_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='responsibility',
        ),
        migrations.AddField(
            model_name='responsibility',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='experience.company'),
        ),
    ]
